* Projet de Physique Numerique: RESEAU DE NEURONES
  Résumé : Ce projet consiste à créer un ensemble de réseaux de neurones, chacun capable de reconnaitre une lettre de l'alphabet.
  Descriptif : Inspirés des neurones biologiques, les réseaux de neurones artificiels sont des systèmes linéaires optimisés grâce à une méthode d'apprentissage pour réaliser une tâche précise. Dans ce projet, on se propose de réaliser une tâche assez simple: reconnaitre des caractères.

** Sources
   file:///home/alexandre/Documents/PN/projet/docs/0505016.pdf un article général sur les réseaux de neurones
   file:///home/alexandre/Documents/PN/projet/docs/CTP3.pdf un article en particulier sur une méthode à implémenter

** Objectifs
   Plusieurs objectifs
*** DONE Binarization
    CLOSED: [2020-09-29 Tue 18:26]
    Convertir des images de lettre en une matrice binaires de 1 et de 0 afin de pouvoir y appliquer des operation matricielle.
    Etat actuel (26/09): la binarization fonctionne mais il reste encore a tester sur differents echantillons afin de voir si les resultats sont exploitale.
    La binarization fonctionne et convertit bien une image en une matrice binaire de taille donne.

*** DONE Apprentissage Machine pour un neurone
    CLOSED: [2020-10-06 Tue 16:36]
    L'apprentissage machine fonctionne, il suffit de lui donner une lettre et un nombre de fichier pour qu'une fonction calcule le poid W.
    Le neuronne est capable de reconnaitre une lettre et de donner un quotient qui indique le niveau de confiance de la reconnaissance.
    Plus ce quotient est elevee (proche de 1) plus le neurone est confiant qu'il s'agit de la bonne lettre.

*** TODO Reseau de neuronne
    Objectifs: plusieurs neurones avec un poid W correspondant chacun a une lettre.
    Calcul des coefficicents: score du candidat, score ideal pour le poid-model et le quotient de reconnaissance.
    
**** DONE Base de donnees EMNIST
     CLOSED: [2020-10-13 Tue 17:47]
    Il ne manque plus que les donnees pour pouvoir mettre en oeuvre le reseau de neuronnes.
    Base de donnees EMNIST obtenues, programme capable de lire et afficher une lettre de la base de donnees
    
**** TODO Implementation de la base de donnees dans le reseau de neurones
     A faire

*** TODO RN pour des mots
    L'objectif ici est de pouvoir detecter des mots et des espaces pour pouvoir numeriser des phrases manuscrite.
